random_seed: 42
batch_size: 196

model:
  n_classes: 10  # number of classes
  img_dim: 28  # image dimension
  z_dim: 100  # noise vector dimension
  dropout: 0.0  # dropout rate

training:
  batch_size: 64  # batch size for training
  num_epochs: 2 # number of epochs
  learning_rate: 0.1  # learning rate for the optimizer
  momentum: 0.5  # momentum factor for SGD
  decay_factor: 1.00004  # gamma for ExponentialLR
  z_dim: 100  # noise vector dimension
  samples_save_frequency: 10  # interval (in epochs) to save resultat of generation
  fid_frequency: 0  # interval (in epochs) to calculate fid score, set 0 to prevent calculations
  fid_num_samples: 100  # number of images to use for fid score calculation

evaluation:
  checkpoints:  # path to saved checkpoint file  (relative to the params.yaml)
    discriminator_path: "../runs/2025-01-08_00-15-35/best_discriminator.pth"
    generator_path: "../runs/2025-01-08_00-59-57/best_generator.pth"
  output_dir: "../eval/"  # directory to save evaluations
  num_samples: 196  # number of images to generate
